### ISSUE TITLE
Add skeleton mobile app

### ISSUE THREAD

**Issue by rob-3** [poop-team/project-monorepo#6]

**Comment by Rikimbili** [comment]
We have a skeleton mobile app directory with a default expo preset already, is this what you are referring to? If so we can close this issue

**Comment by rob-3** [comment]
Have you guys actually talked about and agreed that you're going to do React Native and expo? Everyone (or at least whoever is being responsible for mobile) needs to be on board here.

**Comment by Rikimbili** [comment]
You are right we haven't. The plan was to go over this in tomorrow's meeting but I took the initiative of setting that up since it is an industry standard combo (Expo and React Native). If we arrive at the conclusion that we should change it for something else we'll do so. Let's leave this open until we have a final word then

**Comment by rob-3** [comment]
I will note that native is definitely still more common than React Native. I actually would suggest going for a native app given that we don't need to build both iOS and Android.

Building 2 native apps may be harder than building 1 cross-platform app, but building 1 native app is probably easier than building 1 cross-platform. You won't run into leaky abstractions and you're getting the development experience the vendor intended. That being said, if you're all in on JS, React Native can make sense.

**Comment by Rikimbili** [comment]
Closing. We'll be using React Native
